language: node_js

node_js:
    - "6"
    - "node"
addons:
    apt:
        packages:
            - xvfb

before_install:
    - npm install -g electron-packager
      
install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script : sh -e /etc//init.d/svfb start

script:
    - npm install
    - npm test
    - npm build
